import * as T from './vendor/three.module.js';
import {buildHouse,HOUSE,rooms} from './model.js';

const $=id=>document.getElementById(id),canvas=$('scene'),stage=$('stage');
let renderer;
try{renderer=new T.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'high-performance'});}catch(error){$('loading').innerHTML='<span>This walkthrough needs WebGL.</span><p>Please open it in a browser with graphics acceleration enabled.</p>';throw error;}
renderer.setPixelRatio(Math.min(window.devicePixelRatio,1.65));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;
const scene=new T.Scene();scene.background=new T.Color('#e2e7df');scene.fog=new T.Fog('#e2e7df',28,70);
const camera=new T.PerspectiveCamera(64,1,.06,160);camera.rotation.order='YXZ';
scene.add(new T.HemisphereLight('#fffff4','#b8b3a5',1.8));scene.add(new T.AmbientLight('#fff8ed',.72));
const sun=new T.DirectionalLight('#fff4dc',3.1);sun.position.set(-9,17,8);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-17,right:20,top:20,bottom:-15,near:1,far:45});sun.shadow.normalBias=.025;sun.shadow.bias=-.00012;scene.add(sun);sun.target.position.set(3.5,0,-5);scene.add(sun.target);
const model=buildHouse(scene),keys=new Set();
// Plan coordinates put the rear at positive z; mirror it into north-facing world coordinates.
for(const group of [model.ground,model.upper,model.roof,model.garden,model.decor])group.scale.z=-1;
const state={mode:'walk',floor:0,x:-5.4,z:-9.8,yaw:0,pitch:.14,stairs:false,furniture:true,moved:false};
const orbit={angle:-.67,elevation:.92,distance:26,target:new T.Vector3(4,1.0,5.4)};
const dir=new T.Vector3();let previous=performance.now(),mapTick=0,toastTimeout,pointer=null,frameCount=0,lastDt=0;
function face(x,z){state.yaw=Math.atan2(state.x-x,state.z-z);}
face(1.6,3.1);
function toast(text){$('toast').textContent=text;$('toast').classList.add('visible');clearTimeout(toastTimeout);toastTimeout=setTimeout(()=>$('toast').classList.remove('visible'),3500)}
function hideWelcome(){state.moved=true;$('welcome').classList.add('hidden')}
function setFloorUI(){for(const [id,f] of [['groundFloor',0],['firstFloor',1]]){$(id).classList.toggle('active',state.floor===f);$(id).setAttribute('aria-pressed',String(state.floor===f))}$('mapFloorLabel').textContent=state.floor?'FIRST FLOOR':'GROUND FLOOR';$('levelName').textContent=state.stairs?'STAIRCASE':state.floor?'FIRST FLOOR':'GROUND LEVEL';}
function setMode(mode){state.mode=mode;keys.clear();$('walkMode').classList.toggle('active',mode==='walk');$('overviewMode').classList.toggle('active',mode==='overview');$('walkMode').setAttribute('aria-pressed',String(mode==='walk'));$('overviewMode').setAttribute('aria-pressed',String(mode==='overview'));model.upper.visible=mode==='walk'||state.floor===1;model.roof.visible=mode==='walk';model.decor.visible=mode==='walk';for(const c of model.ceilings)c.visible=mode==='walk';if(mode==='overview'){hideWelcome();orbit.target.y=state.floor?2.4:.6;$('locationName').textContent='House overview';$('keyboardGuide').querySelector('strong').textContent='See how the rooms connect';$('keyboardGuide').querySelector('div:last-child span').textContent='Drag to orbit · scroll to zoom · arrow keys rotate';}else{$('keyboardGuide').querySelector('strong').textContent='Make yourself at home';$('keyboardGuide').querySelector('div:last-child span').textContent='↑ ↓ walk · ← → turn · drag to look';}updateLocation();drawMap();}
function jump(id){clearTimeout(toastTimeout);$('toast').classList.remove('visible');const r=rooms.find(r=>r.id===id);if(!r)return;state.floor=r.floor;state.x=r.point[0];state.z=r.point[1];state.pitch=r.id==='hall'?.03:-.10;state.stairs=false;face(...r.look);hideWelcome();setFloorUI();setMode('walk');$('roomSelect').value=id;updateLocation();canvas.focus({preventScroll:true});}
function floorY(){if(state.stairs)return HOUSE.first*Math.max(0,Math.min(1,(state.z-1.2)/1.60));if(!state.floor)return 0;if(state.z>=6 && state.x<5.9)return HOUSE.bedFloor;return HOUSE.first;}
function pointDistance(px,pz,a,b){const vx=b[0]-a[0],vz=b[1]-a[1],t=Math.max(0,Math.min(1,((px-a[0])*vx+(pz-a[1])*vz)/(vx*vx+vz*vz)));return Math.hypot(px-(a[0]+t*vx),pz-(a[1]+t*vz));}
function blocked(x,z){if(x< -6.5||x>8.7||z< -11.5||z>21.5)return true;
 if(state.floor&&!state.stairs){const inMain=x>.21&&x<7.8&&z>.20&&z<5.88,inBed=x>.82&&x<5.67&&z>=5.88&&z<8.77;if(!inMain&&!inBed)return true;}
 const f=state.stairs?0:state.floor;
 return model.colliders[f].some(c=>pointDistance(x,z,c.a,c.b)<.18+c.r);
}
function move(dx,dz){const nx=state.x+dx,nz=state.z+dz;if(!blocked(nx,state.z))state.x=nx;if(!blocked(state.x,nz))state.z=nz;
 const inStairs=state.x>3.69&&state.x<4.41&&state.z>1.2&&state.z<3.02;
 if(state.stairs){if(state.z>=2.79&&dz>0){state.floor=1;state.stairs=false;state.z=3.08;setFloorUI();toast('First floor · explore the bedrooms and studies')}else if(state.z<=1.21&&dz<0){state.floor=0;state.stairs=false;setFloorUI();}else if(!inStairs){state.stairs=false;setFloorUI();}}
 else if(!state.floor&&inStairs){state.stairs=true;}
 else if(state.floor&&inStairs&&state.z<2.96&&dz<0){state.floor=0;state.stairs=true;setFloorUI();}
}
function updateLocation(){stage.dataset.navigation=JSON.stringify({x:state.x,z:state.z,y:floorY(),floor:state.floor,mode:state.mode,yaw:state.yaw,stairs:state.stairs,frames:frameCount});if(state.mode==='overview')return;let name=state.stairs?'Staircase':state.floor?'Landing':state.z>11.3?'Rear terrace':state.z<0?'Front garden':'Entrance hall';for(const r of rooms){if(r.floor!==state.floor||!r.rect)continue;const [x1,z1,x2,z2]=r.rect;if(state.x>=x1&&state.x<=x2&&state.z>=z1&&state.z<=z2){name=r.name;break}}$('locationName').textContent=name;setFloorUI();}
function drawMap(){const c=$('minimap'),ctx=c.getContext('2d'),w=c.width,h=c.height;ctx.clearRect(0,0,w,h);ctx.fillStyle='#f8f9f3';ctx.fillRect(0,0,w,h);const s=31,ox=73,oy=399;const map=(x,z)=>[ox+x*s,oy-z*s];
 // Rear is at the top, front at the bottom, matching the supplied drawings.
 ctx.fillStyle='#e6eadd';ctx.strokeStyle='#77846e';ctx.lineWidth=2;ctx.beginPath();const footprint=state.floor?[[0,0],[8.01,0],[8.01,6],[5.883,6],[5.883,8.98],[.61,8.98],[.61,6],[0,6]]:[[0,0],[.35,0],[.95,-.75],[2.7,-.75],[3.35,0],[4.75,0],[5.4,-.75],[7.1,-.75],[7.76,0],[8.01,0],[8.01,6],[7.683,6],[7.683,11.51],[.61,11.51],[.61,6],[0,6]];footprint.forEach((p,i)=>{const [x,y]=map(...p);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.closePath();ctx.fill();ctx.stroke();
 ctx.font='14px Arial';ctx.textAlign='center';ctx.textBaseline='middle';const current=$('locationName').textContent;
 for(const r of rooms.filter(r=>r.floor===state.floor&&r.rect)){const [x1,z1,x2,z2]=r.rect,[x,y]=map(x1,z2),ww=(x2-x1)*s,hh=(z2-z1)*s;ctx.fillStyle=current===r.name&&state.mode==='walk'?'#d1ddc6':'#f0f1e8';ctx.fillRect(x,y,ww,hh);ctx.strokeStyle='#a1ad96';ctx.lineWidth=1.4;ctx.strokeRect(x,y,ww,hh);ctx.fillStyle='#68745f';const label=r.id==='shower'?['Steam','shower']:r.id==='reception'?['Reception']:r.id==='sitting'?['Sitting']:r.id==='bed1'?['Bedroom 1']:r.id==='bed2'?['Bedroom 2']:r.id==='dining'?['Dining']:r.name.split(' ').length>1?[r.name]:[r.name];label.forEach((t,i)=>ctx.fillText(t,x+ww/2,y+hh/2+(i-(label.length-1)/2)*17));}
 const [sx,sy]=map(3.63,2.8);ctx.strokeStyle='#839277';for(let i=0;i<7;i++){ctx.beginPath();ctx.moveTo(sx,sy+i*7);ctx.lineTo(sx+27,sy+i*7);ctx.stroke()}ctx.fillStyle='#87947e';ctx.font='11px Arial';ctx.fillText('REAR / GARDEN',w/2,19);ctx.fillText('FRONT',w/2,456);
 if(state.mode==='walk'){let [x,y]=map(state.x,state.z);x=Math.max(15,Math.min(w-15,x));y=Math.max(33,Math.min(436,y));ctx.save();ctx.translate(x,y);ctx.rotate(state.yaw);ctx.fillStyle='#2b5744';ctx.globalAlpha=.13;ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(-15,32);ctx.lineTo(15,32);ctx.closePath();ctx.fill();ctx.globalAlpha=1;ctx.fillStyle='#2b5744';ctx.strokeStyle='#fff';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,7,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.restore();}
}
function resize(){const w=stage.clientWidth,h=stage.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.fov=w<650?74:64;camera.updateProjectionMatrix();}new ResizeObserver(resize).observe(stage);resize();
function animate(now){requestAnimationFrame(animate);const dt=Math.min((now-previous)/1000,.045);previous=now;lastDt=dt;const modal=$('infoDialog').open;
 if(!modal){if(state.mode==='walk'){let forward=0,strafe=0;if(keys.has('ArrowUp')||keys.has('KeyW'))forward++;if(keys.has('ArrowDown')||keys.has('KeyS'))forward--;if(keys.has('KeyA'))strafe--;if(keys.has('KeyD'))strafe++;if(keys.has('ArrowLeft')||keys.has('KeyQ'))state.yaw-=1.45*dt;if(keys.has('ArrowRight')||keys.has('KeyE'))state.yaw+=1.45*dt;const len=Math.max(1,Math.hypot(forward,strafe)),speed=keys.has('ShiftLeft')?2.4:1.55;const dx=(-Math.sin(state.yaw)*forward-Math.cos(state.yaw)*strafe)*dt*speed/len,dz=(-Math.cos(state.yaw)*forward+Math.sin(state.yaw)*strafe)*dt*speed/len;if(dx||dz)move(dx,dz);if(keys.size)hideWelcome();camera.position.set(state.x,floorY()+1.63,-state.z);camera.rotation.set(state.pitch,Math.PI-state.yaw,0,'YXZ');}
 else{if(keys.has('ArrowLeft'))orbit.angle-=dt*.7;if(keys.has('ArrowRight'))orbit.angle+=dt*.7;if(keys.has('ArrowUp'))orbit.distance=Math.max(10,orbit.distance-dt*4);if(keys.has('ArrowDown'))orbit.distance=Math.min(32,orbit.distance+dt*4);const distance=orbit.distance*Math.max(1,1.35/camera.aspect);camera.position.set(orbit.target.x+Math.sin(orbit.angle)*distance*Math.cos(orbit.elevation),orbit.target.y+Math.sin(orbit.elevation)*distance,-orbit.target.z-Math.cos(orbit.angle)*distance*Math.cos(orbit.elevation));camera.lookAt(orbit.target.x,orbit.target.y,-orbit.target.z);}}
 if(now-mapTick>100){updateLocation();drawMap();mapTick=now}renderer.render(scene,camera);frameCount++;
}requestAnimationFrame(animate);setTimeout(()=>$('loading').classList.add('done'),300);
const supported=new Set(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyW','KeyS','KeyA','KeyD','KeyQ','KeyE','ShiftLeft']);
window.addEventListener('keydown',e=>{if($('infoDialog').open||['SELECT','INPUT','TEXTAREA'].includes(e.target.tagName))return;if(supported.has(e.code)){e.preventDefault();if(!keys.has(e.code)&&state.mode==='walk'){let f=0,s=0;if(e.code==='ArrowUp'||e.code==='KeyW')f=1;if(e.code==='ArrowDown'||e.code==='KeyS')f=-1;if(e.code==='KeyA')s=-1;if(e.code==='KeyD')s=1;move(((-Math.sin(state.yaw)*f)-Math.cos(state.yaw)*s)*.075,((-Math.cos(state.yaw)*f)+Math.sin(state.yaw)*s)*.075);if(e.code==='ArrowLeft'||e.code==='KeyQ')state.yaw-=.055;if(e.code==='ArrowRight'||e.code==='KeyE')state.yaw+=.055;hideWelcome();}keys.add(e.code)}if(e.code==='Escape')keys.clear()});window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>keys.clear());document.addEventListener('visibilitychange',()=>{keys.clear();previous=performance.now()});
canvas.addEventListener('pointerdown',e=>{canvas.focus({preventScroll:true});pointer={id:e.pointerId,x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(!pointer||e.pointerId!==pointer.id)return;const dx=e.clientX-pointer.x,dy=e.clientY-pointer.y;pointer.x=e.clientX;pointer.y=e.clientY;if(state.mode==='walk'){state.yaw+=dx*.004;state.pitch=Math.max(-1.05,Math.min(.9,state.pitch-dy*.003));}else{orbit.angle-=dx*.006;orbit.elevation=Math.max(.35,Math.min(1.45,orbit.elevation+dy*.004));}if(Math.abs(dx)+Math.abs(dy)>3)hideWelcome()});const endPointer=()=>pointer=null;canvas.addEventListener('pointerup',endPointer);canvas.addEventListener('pointercancel',endPointer);canvas.addEventListener('wheel',e=>{if(state.mode==='overview'){e.preventDefault();orbit.distance=Math.max(10,Math.min(32,orbit.distance+e.deltaY*.018))}},{passive:false});
$('enterHouse').onclick=()=>jump('hall');$('walkMode').onclick=()=>{setMode('walk');hideWelcome();canvas.focus()};$('overviewMode').onclick=()=>{setMode('overview');canvas.focus()};$('groundFloor').onclick=()=>{if(state.mode==='overview'){state.floor=0;setFloorUI();setMode('overview')}else jump('hall')};$('firstFloor').onclick=()=>{if(state.mode==='overview'){state.floor=1;setFloorUI();setMode('overview')}else jump('landing')};$('roomSelect').onchange=e=>{if(e.target.value)jump(e.target.value)};
$('resetButton').onclick=()=>{state.x=-5.4;state.z=-9.8;state.floor=0;state.pitch=.14;state.stairs=false;state.moved=false;face(1.6,3.1);setMode('walk');$('roomSelect').value='';$('welcome').classList.remove('hidden');canvas.focus()};
$('furnitureButton').onclick=()=>{state.furniture=!state.furniture;model.furniture.forEach(g=>g.visible=state.furniture);$('furnitureButton').setAttribute('aria-pressed',String(state.furniture));$('furnitureButton').querySelector('span').textContent=state.furniture?'On':'Off';toast(state.furniture?'Illustrative furniture shown':'Furniture hidden to see the spaces')};
$('mapToggle').onclick=()=>{const hidden=$('mapCard').classList.toggle('collapsed');$('mapToggle').textContent=hidden?'+':'−';$('mapToggle').setAttribute('aria-expanded',String(!hidden));$('mapToggle').setAttribute('aria-label',hidden?'Expand floor map':'Collapse floor map')};
$('minimap').addEventListener('click',e=>{const b=e.currentTarget.getBoundingClientRect(),mx=(e.clientX-b.left)*400/b.width,mz=(e.clientY-b.top)*500/b.height,x=(mx-73)/31,z=(399-mz)/31;const r=rooms.find(r=>r.floor===state.floor&&r.rect&&x>=r.rect[0]&&x<=r.rect[2]&&z>=r.rect[1]&&z<=r.rect[3]);if(r)jump(r.id)});
$('fullscreenButton').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{toast('Full screen is unavailable here. Open the page in a browser.')}};
$('infoButton').onclick=()=>{keys.clear();$('infoDialog').showModal()};document.querySelectorAll('.close-dialog,.close-info').forEach(b=>b.onclick=()=>$('infoDialog').close());$('infoDialog').addEventListener('click',e=>{if(e.target===$('infoDialog')){const b=$('infoDialog').getBoundingClientRect();if(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom)$('infoDialog').close()}});
document.querySelectorAll('[data-key]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);const k=b.dataset.key;if(state.mode==='walk'){if(k==='ArrowUp'||k==='ArrowDown'){const f=k==='ArrowUp'?1:-1;move(-Math.sin(state.yaw)*f*.10,-Math.cos(state.yaw)*f*.10)}if(k==='ArrowLeft')state.yaw-=.10;if(k==='ArrowRight')state.yaw+=.10;}else{if(k==='ArrowLeft')orbit.angle-=.10;if(k==='ArrowRight')orbit.angle+=.10;if(k==='ArrowUp')orbit.distance=Math.max(10,orbit.distance-.4);if(k==='ArrowDown')orbit.distance=Math.min(32,orbit.distance+.4);}keys.add(k);hideWelcome()});for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>keys.delete(b.dataset.key))});
// Read-only diagnostics for local verification; movement still uses normal input.
Object.defineProperty(window,'houseDiagnostics',{get:()=>({mode:state.mode,floor:state.floor,x:state.x,z:state.z,y:floorY(),yaw:state.yaw,stairs:state.stairs,frames:frameCount,dt:lastDt,location:$('locationName').textContent,triangles:renderer.info.render.triangles,drawCalls:renderer.info.render.calls})});
updateLocation();drawMap();
